name: PraxiCloud Core Metrics Providers Build Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-library:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        source-url: ${{secrets.REPO_NUGET_SOURCE}}
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        NUGET_SOURCE: ${{secrets.REPO_NUGET_SOURCE}}
        NUGET_USER: ${{secrets.REPO_USER_NAME}}
    - name: Update Packaging Version
      run: sed -i "s/<Version>1.0.1<\/Version>/<Version>${{ github.event.inputs.library-version }}<\/Version>/g" ./src/common.props      
    - name: Install Nuget Dependencies
      run: dotnet restore ./src/praxicloud.core.metrics.providers.solution.sln
    - name: Build Library and Test Projects
      run: dotnet build --configuration Release --no-restore ./src/praxicloud.core.metrics.providers.solution.sln
    - name: Test Library Prometheus
      run: dotnet test --no-restore --verbosity normal ./src/praxicloud.core.metrics.prometheus.tests/praxicloud.core.metrics.prometheus.tests.csproj
    - name: Package Application Insights library
      run: dotnet pack --configuration Release ./src/praxicloud.core.metrics.applicationinsights/praxicloud.core.metrics.applicationinsights.csproj
    - name: Package Prometheus library
      run: dotnet pack --configuration Release ./src/praxicloud.core.metrics.prometheus/praxicloud.core.metrics.prometheus.csproj
    - name: Push Application Insights library package to GitHub NUGET Feed
      run: nuget push ./src/praxicloud.core.metrics.applicationinsights/bin/Release/*.nupkg -SkipDuplicate -ApiKey ${{secrets.GITHUB_TOKEN}}   
    - name: Push Prometheus library package to GitHub NUGET Feed
      run: nuget push ./src/praxicloud.core.metrics.prometheus/bin/Release/*.nupkg -SkipDuplicate -ApiKey ${{secrets.GITHUB_TOKEN}}   
